export enum BlackboardKeys {
  ENEMY_CHAMPIONS = 'enemyChampions',
  ENEMY_TOWERS = 'enemyTowers',
  TARGET_CHAMPION_CANDIDATES = 'targetChampionCandidates',
  TARGET_CHAMPION = 'targetChampion',
  TARGET_TOWER = 'targetTower',
  TARGET_HEALTH_PACK = 'targetHealthPack',
  NEXUS = 'nexus',
  ENEMY_NEXUS = 'enemyNexus',
  ENEMY_MINIONS = 'enemyMinions',
  FRIENDLY_MINIONS = 'friendlyMinions',
  FRIENDLY_TOWERS = 'friendlyTowers',
  TARGET_MINION = 'targetMinion',
  ABILITY_TO_USE = 'abilityToUse',
  CHAMPION = 'champion',
  SIDE = 'side',
}
